name: Coverage
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
env:
  PYTHON_VERSION: '3.7'
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup python ${{ env.PYTHON_VERSION }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ env.PYTHON_VERSION }}
    - name: Install dependencies
      run: python -m pip install -e .
    - name: Install test dependencies
      run: python -m pip install pytest pytest-cov
    - name: Run tests
      run: python -m pytest --cov=rsgt --cov-report=term --cov-report=xml tests/
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v1
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
